version: 2

jobs:
  install:
    working_directory: ~/enki-project
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/enki-project
      - run:
          name: install
          command: |
            npm init --yes;
            npm install cowsay
      - persist_to_workspace:
          root: ~/enki-project
          paths: ./node_modules

  use:
    working_directory: ~/enki-project
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ~/enki-project
      - run:
          name: use
          command: |
            ./node_modules/.bin/cowsay CicleCI is cool!
workflows:
  version: 2
  install_use:
    jobs:
      - install
      - use:
          requires:
            - install
